import type { Question, QuestionRole, QuestionType, ShowCondition, ShowRule } from './questions'

const WEBSITE = [
  'Website design + development',
  'Webflow development',
  'Website redesign',
  'Migration to Webflow',
  'Branding + website',
]

const REFERENCES = ['Website design + development', 'Website redesign', 'Branding + website']
const AGENCY = ['Agency partner', 'Representing a client']
const REDESIGN_PATHS = ['Website redesign', 'Existing Webflow improvements', 'Migration to Webflow']

function eq(questionId: string, value: string): ShowCondition {
  return { questionId, operator: 'eq', value }
}

function neq(questionId: string, value: string): ShowCondition {
  return { questionId, operator: 'neq', value }
}

function inn(questionId: string, value: string[]): ShowCondition {
  return { questionId, operator: 'in', value }
}

function contains(questionId: string, value: string): ShowCondition {
  return { questionId, operator: 'contains', value }
}

function answered(questionId: string): ShowCondition {
  return { questionId, operator: 'answered' }
}

function and(...conditions: ShowCondition[]): ShowRule {
  return { combinator: 'and', conditions }
}

function or(...conditions: ShowCondition[]): ShowRule {
  return { combinator: 'or', conditions }
}

type SeedInput = {
  id: string
  kicker: string
  title: string
  description?: string
  placeholder?: string
  type: QuestionType
  required?: boolean
  options?: string[]
  showRule?: ShowRule
  role?: QuestionRole
}

function seedQuestion(input: SeedInput, sortOrder: number): Question {
  return {
    id: input.id,
    sortOrder,
    kicker: input.kicker,
    title: input.title,
    description: input.description ?? null,
    placeholder: input.placeholder ?? null,
    type: input.type,
    required: input.required ?? false,
    options: input.options ?? [],
    showRule: input.showRule ?? null,
    role: input.role ?? null,
    isActive: true,
  }
}

const RAW: SeedInput[] = [
  {
    id: 'Q01',
    kicker: 'About you',
    title: 'What is your full name?',
    type: 'text',
    required: true,
    placeholder: 'Your name',
    role: 'full_name',
  },
  {
    id: 'Q02',
    kicker: 'About you',
    title: 'What is your work email?',
    type: 'email',
    required: true,
    placeholder: 'you@company.com',
    role: 'email',
  },
  {
    id: 'Q03',
    kicker: 'About you',
    title: 'What is your company name?',
    type: 'text',
    required: true,
    placeholder: 'Company name',
    role: 'company',
  },
  {
    id: 'Q04',
    kicker: 'Relationship',
    title: 'How will we be working together?',
    type: 'single',
    required: true,
    options: ['Directly with our company', 'Agency partner', 'Representing a client', 'Not sure yet'],
    role: 'relationship',
  },
  {
    id: 'Q05',
    kicker: 'Project',
    title: 'What are you primarily looking for help with?',
    description: 'Choose the closest fit. The form will adapt from here.',
    type: 'single',
    required: true,
    options: [
      'Website design + development',
      'Webflow development',
      'Website redesign',
      'Migration to Webflow',
      'Existing Webflow improvements',
      'SEO / AEO',
      'Branding + website',
      'Not sure yet',
    ],
    role: 'project_type',
  },
  {
    id: 'Q06',
    kicker: 'Goal',
    title: 'What is the main goal of this project?',
    type: 'multi',
    required: true,
    options: [
      'Generate more leads',
      'Improve conversions',
      'Strengthen the brand',
      'Launch something new',
      'Improve SEO / search visibility',
      'Improve website performance',
      'Make content easier to manage',
      'Move to Webflow',
    ],
  },
  {
    id: 'Q07',
    kicker: 'Context',
    title: 'Why are you considering this project now?',
    description:
      'A short answer is enough. We want to understand what changed or what is creating urgency.',
    type: 'textarea',
    required: true,
    placeholder:
      'For example: rebrand, new launch, current site is hard to manage, poor SEO, design is outdated...',
  },
  {
    id: 'Q08',
    kicker: 'Success',
    title: 'What would make this project successful for you?',
    description: 'Think about the outcome rather than the deliverable.',
    type: 'textarea',
    placeholder:
      'For example: more qualified leads, easier content publishing, stronger enterprise credibility...',
  },
  {
    id: 'Q53',
    kicker: 'Audience',
    title: 'Who is the primary target audience for this project?',
    description:
      'Tell us who the website should persuade or serve: customer type, role, segment or buyer.',
    type: 'textarea',
    required: true,
    placeholder:
      'For example: marketing leaders at 50–500 person SaaS companies, homeowners in Boston, enterprise procurement teams...',
    showRule: and(answered('Q05'), neq('Q05', 'Not sure yet')),
  },
  {
    id: 'Q54',
    kicker: 'Geography',
    title: 'Which geographies or markets are most important?',
    description: 'Countries, regions or cities the website should primarily support or speak to.',
    type: 'textarea',
    required: true,
    placeholder:
      'For example: United States and Canada, DACH, London, global English-speaking market...',
    showRule: and(answered('Q05'), neq('Q05', 'Not sure yet')),
  },
  {
    id: 'Q55',
    kicker: 'Priority',
    title: 'What should be most prominent or prioritized on the website?',
    description:
      'Your hero product, service, offer, capability, page, campaign, proof point or anything visitors should notice first.',
    type: 'textarea',
    required: true,
    placeholder:
      'For example: our enterprise AI platform, Book a Demo, our new healthcare service, a specific product line...',
    showRule: and(inn('Q05', REFERENCES)),
  },
  {
    id: 'Q09',
    kicker: 'Current website',
    title: 'Do you currently have a website?',
    type: 'single',
    required: true,
    options: ['Yes', 'No'],
  },
  {
    id: 'Q10',
    kicker: 'Current website',
    title: 'Please share the current website URL.',
    type: 'url',
    required: true,
    placeholder: 'https://...',
    showRule: and(eq('Q09', 'Yes')),
  },
  {
    id: 'Q11',
    kicker: 'Current website',
    title: 'What platform is it built on?',
    type: 'single',
    options: [
      'Webflow',
      'WordPress',
      'Shopify',
      'Wix',
      'Framer',
      'Squarespace',
      'Custom-built',
      'Other',
      'Not sure',
    ],
    showRule: and(eq('Q09', 'Yes')),
  },
  {
    id: 'Q56',
    kicker: 'Current website',
    title: 'What would you most like to improve about the current website?',
    type: 'multi',
    options: [
      'Visual design',
      'Messaging / content',
      'User experience',
      'Conversion',
      'Mobile responsiveness',
      'Performance',
      'CMS / content management',
      'SEO',
      'Navigation / structure',
      'Animations / interactions',
      'Integrations',
      'Complete rethink',
      'Other',
    ],
    showRule: and(eq('Q09', 'Yes'), inn('Q05', REDESIGN_PATHS)),
  },
  {
    id: 'Q12',
    kicker: 'Scope',
    title: 'Approximately how many pages are in scope?',
    type: 'single',
    required: true,
    options: ['1–5', '6–10', '11–20', '21–40', '40+', 'Not sure yet'],
    showRule: and(inn('Q05', WEBSITE)),
  },
  {
    id: 'Q13',
    kicker: 'Scope',
    title: 'How many unique page designs or templates do you expect?',
    description: 'For example, 50 CMS pages may still use only 5 unique templates.',
    type: 'single',
    options: ['1–3', '4–6', '7–10', '11–20', '20+', 'Not sure yet'],
    showRule: and(inn('Q05', WEBSITE)),
  },
  {
    id: 'Q14',
    kicker: 'Sitemap',
    title: 'Is the sitemap or page structure ready?',
    type: 'single',
    required: true,
    options: ['Finalized', 'Mostly ready', 'Still in progress', 'We need help defining it'],
    showRule: and(inn('Q05', WEBSITE)),
  },
  {
    id: 'Q15',
    kicker: 'Sitemap',
    title: 'Please share the sitemap link.',
    description: 'A Google Doc, Sheet, Figma page, Notion page or any accessible link works.',
    type: 'url',
    placeholder: 'https://...',
    showRule: and(inn('Q14', ['Finalized', 'Mostly ready'])),
  },
  {
    id: 'Q16',
    kicker: 'Design status',
    title: 'What is the current design status?',
    type: 'single',
    required: true,
    options: [
      'No designs yet',
      'Wireframes ready',
      'Some pages designed',
      'Most pages designed',
      'Finalized designs',
    ],
    showRule: and(inn('Q05', WEBSITE)),
  },
  {
    id: 'Q17',
    kicker: 'Design link',
    title: 'Please share the Figma or design link.',
    type: 'url',
    placeholder: 'https://figma.com/...',
    showRule: and(inn('Q16', ['Some pages designed', 'Most pages designed', 'Finalized designs'])),
  },
  {
    id: 'Q18',
    kicker: 'Responsive design',
    title: 'Do the designs include responsive states?',
    type: 'single',
    options: [
      'Desktop + Tablet + Mobile',
      'Desktop + Mobile',
      'Desktop only',
      'Partially',
      'Not sure',
    ],
    showRule: and(answered('Q17')),
  },
  {
    id: 'Q19',
    kicker: 'References',
    title: 'Please share 2–5 websites you like as references.',
    description: 'One URL per line is perfect.',
    type: 'textarea',
    placeholder: 'https://reference-one.com\nhttps://reference-two.com',
    showRule: and(inn('Q05', REFERENCES)),
  },
  {
    id: 'Q20',
    kicker: 'References',
    title: 'What specifically do you like about those references?',
    type: 'textarea',
    placeholder: 'Typography, layout, motion, navigation, overall premium feel...',
    showRule: and(answered('Q19')),
  },
  {
    id: 'Q21',
    kicker: 'Competitors',
    title: 'Please share your main competitor websites.',
    description: 'This helps us understand positioning, category expectations and SEO context.',
    type: 'textarea',
    placeholder: 'https://competitor-one.com\nhttps://competitor-two.com',
    showRule: and(answered('Q05'), neq('Q05', 'Not sure yet')),
  },
  {
    id: 'Q22',
    kicker: 'Content',
    title: 'Who will be responsible for providing the content?',
    type: 'single',
    required: true,
    options: [
      'Our internal team',
      'Appsrow',
      'Another agency / copywriter',
      'Reuse existing website content',
      'Shared responsibility',
      'Not decided yet',
    ],
    showRule: and(answered('Q05'), neq('Q05', 'Not sure yet')),
  },
  {
    id: 'Q23',
    kicker: 'Content',
    title: 'What is the current content status?',
    type: 'single',
    required: true,
    options: [
      'Final content is ready',
      'Most content is ready',
      'Draft content is available',
      'Reuse existing content',
      'Existing content needs improvement',
      'Content has not started',
    ],
    showRule: and(answered('Q22')),
  },
  {
    id: 'Q65',
    kicker: 'Content',
    title: 'Will content from the existing website be reused?',
    type: 'single',
    options: [
      'Mostly',
      'Partially',
      'No, we are creating new content',
      'No existing website',
      'Not decided yet',
    ],
    showRule: and(inn('Q05', WEBSITE), answered('Q22')),
  },
  {
    id: 'Q24',
    kicker: 'Content support',
    title: 'Do you need help with copywriting or content structure?',
    type: 'single',
    options: ['Yes', 'No', 'Maybe / to discuss'],
    showRule: and(
      inn('Q23', [
        'Draft content is available',
        'Existing content needs improvement',
        'Content has not started',
      ])
    ),
  },
  {
    id: 'Q48',
    kicker: 'Agency / white-label',
    title: 'Do you require Appsrow to work white-label?',
    type: 'single',
    options: ['Yes', 'No', 'To discuss'],
    showRule: and(inn('Q04', AGENCY)),
  },
  {
    id: 'Q49',
    kicker: 'Agency / white-label',
    title: 'Will Appsrow communicate directly with the end client?',
    type: 'single',
    options: ['Yes', 'No', 'Selected calls only', 'Not decided'],
    showRule: and(inn('Q04', AGENCY)),
  },
  {
    id: 'Q50',
    kicker: 'Agency / white-label',
    title: 'Are there internal frameworks, QA standards or delivery rules we should follow?',
    type: 'textarea',
    placeholder: 'Framework, naming convention, QA process, communication rules...',
    showRule: and(inn('Q04', AGENCY)),
  },
  {
    id: 'Q25',
    kicker: 'Webflow',
    title: 'Is Webflow confirmed as the development platform?',
    type: 'single',
    required: true,
    options: ['Yes', 'Open to recommendation', 'No / not decided'],
    showRule: and(inn('Q05', WEBSITE)),
  },
  {
    id: 'Q26',
    kicker: 'Webflow',
    title: 'Do you have a preferred Webflow framework?',
    type: 'single',
    options: ['Client-First', 'MAST', 'Lumos', 'Our internal framework', 'No preference', 'Not sure'],
    showRule: and(inn('Q05', WEBSITE)),
  },
  {
    id: 'Q27',
    kicker: 'CMS',
    title: 'Will the site require CMS-driven content?',
    type: 'single',
    options: ['Yes', 'No', 'Not sure'],
    showRule: and(inn('Q05', WEBSITE)),
  },
  {
    id: 'Q28',
    kicker: 'CMS',
    title: 'Which CMS content types are required?',
    type: 'multi',
    options: [
      'Blog / Resources',
      'Case studies',
      'Projects / Portfolio',
      'Team',
      'Services',
      'Locations',
      'Jobs',
      'Products',
      'Integrations',
      'Other',
    ],
    showRule: and(eq('Q27', 'Yes')),
  },
  {
    id: 'Q60',
    kicker: 'CMS scale',
    title: 'Approximately how much CMS content will need to be added or imported?',
    type: 'single',
    options: ['Under 25 items', '25–100', '100–500', '500–1,000', '1,000+', 'Not sure'],
    showRule: and(eq('Q27', 'Yes')),
  },
  {
    id: 'Q61',
    kicker: 'CMS migration',
    title: 'Does any CMS content need to be imported from another system?',
    type: 'single',
    options: ['Yes', 'No', 'Not sure'],
    showRule: and(eq('Q27', 'Yes')),
  },
  {
    id: 'Q62',
    kicker: 'Scalable CMS',
    title: 'Are you planning to create pages at scale from structured data?',
    description:
      'For example: location pages, directories, integrations, comparisons or other programmatic SEO pages.',
    type: 'single',
    options: ['Yes', 'No', 'Not sure'],
    showRule: and(eq('Q27', 'Yes'), inn('Q60', ['500–1,000', '1,000+'])),
  },
  {
    id: 'Q63',
    kicker: 'Scalable CMS',
    title: 'Approximately how many scalable or programmatic pages are expected?',
    type: 'single',
    options: ['Under 100', '100–500', '500–1,000', '1,000–5,000', '5,000+', 'Not sure'],
    showRule: and(eq('Q62', 'Yes')),
  },
  {
    id: 'Q64',
    kicker: 'Source data',
    title: 'Where does the source data currently live?',
    type: 'single',
    options: ['CSV / Excel', 'Airtable', 'Database', 'API', 'Existing CMS', 'Other', 'Not sure'],
    showRule: and(eq('Q62', 'Yes')),
  },
  {
    id: 'Q29',
    kicker: 'Interactions',
    title: 'What level of animation or interaction is expected?',
    type: 'single',
    options: [
      'None',
      'Basic Webflow interactions',
      'Advanced Webflow interactions',
      'GSAP / custom animation',
      '3D / Spline',
      'Not sure',
    ],
    showRule: and(inn('Q05', WEBSITE)),
  },
  {
    id: 'Q30',
    kicker: 'Integrations',
    title: 'Are third-party integrations required?',
    type: 'multi',
    options: [
      'CRM',
      'HubSpot',
      'Salesforce',
      'Calendly / booking',
      'Custom forms',
      'Analytics / GTM',
      'ATS / Greenhouse',
      'API',
      'Ecommerce',
      'None',
      'Not sure',
    ],
    showRule: and(inn('Q05', WEBSITE)),
  },
  {
    id: 'Q57',
    kicker: 'Functionality',
    title: 'Does the website require any special functionality?',
    description: 'Choose anything that could affect scope beyond standard marketing pages.',
    type: 'multi',
    options: [
      'Advanced forms',
      'Search',
      'Filtering / sorting',
      'Ecommerce',
      'Membership / login',
      'Booking',
      'Calculator / interactive tool',
      'Interactive map',
      'Job listings',
      'Resource library',
      'Gated content',
      'Multi-language',
      'Custom API functionality',
      'Other',
      'None',
      'Not sure',
    ],
    showRule: and(inn('Q05', WEBSITE)),
  },
  {
    id: 'Q58',
    kicker: 'Localization',
    title: 'Will the website need multiple languages?',
    type: 'single',
    options: ['No', 'Yes', 'Possibly later', 'Not sure'],
    showRule: and(inn('Q05', WEBSITE)),
  },
  {
    id: 'Q59',
    kicker: 'Localization',
    title: 'Which languages are required?',
    type: 'text',
    placeholder: 'For example: English, German and French',
    showRule: and(eq('Q58', 'Yes')),
  },
  {
    id: 'Q31',
    kicker: 'Migration',
    title: 'What platform are you migrating from?',
    type: 'single',
    required: true,
    options: ['WordPress', 'Wix', 'Squarespace', 'Shopify', 'Framer', 'Custom-built', 'Other'],
    showRule: and(eq('Q05', 'Migration to Webflow')),
  },
  {
    id: 'Q32',
    kicker: 'Migration',
    title: 'What should happen to the current design?',
    type: 'single',
    required: true,
    options: [
      'Keep it almost the same',
      'Improve the existing design',
      'Complete redesign',
      'Not sure yet',
    ],
    showRule: and(eq('Q05', 'Migration to Webflow')),
  },
  {
    id: 'Q33',
    kicker: 'Migration',
    title: 'Approximately how many CMS items need to be migrated?',
    type: 'single',
    options: ['None', 'Under 50', '50–250', '250–1,000', '1,000+', 'Not sure'],
    showRule: and(eq('Q05', 'Migration to Webflow')),
  },
  {
    id: 'Q34',
    kicker: 'SEO preservation',
    title: 'Do existing URLs and SEO rankings need to be preserved?',
    type: 'single',
    options: ['Yes, critical', 'Yes', 'Not particularly', 'Not sure'],
    showRule: and(eq('Q05', 'Migration to Webflow')),
  },
  {
    id: 'Q35',
    kicker: 'Content migration',
    title: 'Should Appsrow migrate the existing content as well?',
    type: 'single',
    options: ['Yes', 'No', 'Partially', 'Not sure'],
    showRule: and(eq('Q05', 'Migration to Webflow')),
  },
  {
    id: 'Q36',
    kicker: 'Existing Webflow',
    title: 'What kind of help do you need?',
    type: 'multi',
    required: true,
    options: [
      'Bug fixes',
      'Responsive issues',
      'CMS improvements',
      'New pages',
      'Performance',
      'SEO / schema',
      'Design improvements',
      'Animations',
      'Integrations',
      'Ongoing development',
    ],
    showRule: and(eq('Q05', 'Existing Webflow improvements')),
  },
  {
    id: 'Q37',
    kicker: 'Existing Webflow',
    title: 'What are the most important issues you want us to address?',
    type: 'textarea',
    required: true,
    placeholder: 'Tell us the issues that matter most...',
    showRule: and(eq('Q05', 'Existing Webflow improvements')),
  },
  {
    id: 'Q38',
    kicker: 'Support model',
    title: 'What kind of engagement are you looking for?',
    type: 'single',
    options: [
      'One-time fix',
      'Defined improvement project',
      'Ongoing monthly support',
      'Not sure yet',
    ],
    showRule: and(eq('Q05', 'Existing Webflow improvements')),
  },
  {
    id: 'Q39',
    kicker: 'Access',
    title: 'Can Appsrow receive Webflow access for an initial review?',
    type: 'single',
    options: ['Yes', 'After NDA', 'Later in the process', 'No'],
    showRule: and(eq('Q05', 'Existing Webflow improvements')),
  },
  {
    id: 'Q40',
    kicker: 'SEO / AEO',
    title: 'What are you primarily looking to improve?',
    type: 'multi',
    required: true,
    options: [
      'Organic traffic',
      'Keyword rankings',
      'Qualified leads',
      'Technical SEO',
      'Local SEO',
      'Content strategy',
      'AEO / AI visibility',
      'Schema / structured data',
      'Site architecture',
    ],
    showRule: or(eq('Q05', 'SEO / AEO'), contains('Q06', 'Improve SEO / search visibility')),
  },
  {
    id: 'Q41',
    kicker: 'SEO / AEO',
    title: 'Which markets or geographies are most important?',
    type: 'textarea',
    placeholder: 'US, UK, Germany... or specific cities/regions',
    showRule: or(eq('Q05', 'SEO / AEO'), contains('Q06', 'Improve SEO / search visibility')),
  },
  {
    id: 'Q42',
    kicker: 'SEO / AEO',
    title: 'Are you currently doing SEO?',
    type: 'single',
    options: ['Yes, internally', 'Yes, with an agency', 'Some basic SEO', 'No', 'Not sure'],
    showRule: or(eq('Q05', 'SEO / AEO'), contains('Q06', 'Improve SEO / search visibility')),
  },
  {
    id: 'Q43',
    kicker: 'SEO / AEO',
    title: 'Do you have Google Analytics and Search Console set up?',
    type: 'single',
    options: ['Both', 'Google Analytics only', 'Search Console only', 'Neither', 'Not sure'],
    showRule: or(eq('Q05', 'SEO / AEO'), contains('Q06', 'Improve SEO / search visibility')),
  },
  {
    id: 'Q44',
    kicker: 'AEO',
    title: 'Which AI-search platforms matter most to you?',
    type: 'multi',
    options: ['ChatGPT', 'Google AI Overviews', 'Perplexity', 'Gemini', 'Copilot', 'Other / not sure'],
    showRule: and(contains('Q40', 'AEO / AI visibility')),
  },
  {
    id: 'Q45',
    kicker: 'Branding',
    title: 'What best describes the current brand situation?',
    type: 'single',
    required: true,
    options: [
      'Starting from scratch',
      'Existing brand needs refinement',
      'Full rebrand',
      'Established brand, website only',
    ],
    showRule: and(eq('Q05', 'Branding + website')),
  },
  {
    id: 'Q46',
    kicker: 'Branding',
    title: 'Do you already have a logo and brand guidelines?',
    type: 'single',
    options: ['Both', 'Logo only', 'Partial guidelines', 'Neither'],
    showRule: and(eq('Q05', 'Branding + website')),
  },
  {
    id: 'Q47',
    kicker: 'Branding',
    title: 'How would you like people to perceive the brand?',
    type: 'textarea',
    placeholder: 'Premium, technical, trustworthy, bold, simple, enterprise-ready...',
    showRule: and(eq('Q05', 'Branding + website')),
  },
  {
    id: 'Q66',
    kicker: 'Project materials',
    title: 'Do you have any project files or documentation you would like us to review?',
    description:
      'Share a link to a brief, RFP, brand guide, audit, content file or other useful material.',
    type: 'url',
    placeholder: 'https://...',
  },
  {
    id: 'Q51',
    kicker: 'Timeline',
    title: 'When would you ideally like to launch or have this work completed?',
    type: 'single',
    required: true,
    options: [
      'Within 2 weeks',
      'Within 1 month',
      'Within 1–2 months',
      'Within 3 months',
      '3+ months',
      'No fixed date yet',
    ],
  },
  {
    id: 'Q67',
    kicker: 'Timeline',
    title: 'Is this a fixed deadline?',
    type: 'single',
    options: ['Yes', 'No', 'Some flexibility', 'Not sure'],
  },
  {
    id: 'Q68',
    kicker: 'Timeline',
    title: 'What is driving the deadline?',
    description:
      'This helps us understand whether the date is tied to a launch, event, campaign or internal commitment.',
    type: 'textarea',
    placeholder:
      'For example: product launch on October 15, investor announcement, conference, migration cutover...',
    showRule: and(eq('Q67', 'Yes')),
  },
  {
    id: 'Q69',
    kicker: 'Requirements',
    title:
      'Are there any procurement, security, legal, privacy or compliance requirements we should know about?',
    description: 'For example: NDA, GDPR, HIPAA, WCAG, vendor onboarding or security review.',
    type: 'textarea',
    placeholder: 'Leave blank if none.',
  },
  {
    id: 'Q52',
    kicker: 'Investment',
    title: 'What investment range have you allocated for this project?',
    description: 'Optional. This helps us recommend the right scope and engagement model.',
    type: 'single',
    options: [
      'Under $2,500',
      '$2,500–$5,000',
      '$5,000–$10,000',
      '$10,000–$25,000',
      '$25,000+',
      'Not decided yet',
      'Prefer to discuss',
    ],
  },
]

export const SEED_QUESTIONS: Question[] = RAW.map((item, index) => seedQuestion(item, index + 1))
